@Requests.api_HostAddress = https://localhost:5171

# Get all requests
GET {{Requests.api_HostAddress}}/api/requests/list
Accept: application/json

###

# Create new request
POST {{Requests.api_HostAddress}}/api/requests/create
Content-Type: application/json

{
  "requestorName": "יוסי כהן",
  "requestTopic": "בקשה לקבלת מידע",
  "requestDescription": "אני מבקש לקבל מידע על הליך הגשת תביעה"
}

###
